# Site settings
author: Deanna Kelley
title: Coding for Muggles
header-img: img/home-bg.png
email: deanna.georges@gmail.com
copyright_name: Deanna Kelley
description: > # this means to ignore newlines until "baseurl:"
  A Wizard Learns to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dg203087

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
